
export const categories = [
  "Agricultural Products",
  "Manufactured Goods",
  "Minerals and Raw Materials",
  "Chemicals and Pharmaceuticals",
  "Technology and Software",
  "Luxury Goods",
  "Consumer Goods",
  "Textiles and Fabrics",
  "Art and Craft",
  "Vehicles and Parts",
  "Energy Resources",
  "Machinery and Equipment",
  "Processed Food and Beverages",
  "Others",
] as const

export const propertyType = [
  { value: 'house', label: 'Houses' },
  { value: 'flat', label: 'Flats' },
  { value: 'apartment', label: 'Apartments' },
  { value: 'townhouse', label: 'Townhouses' },
  { value: 'villa', label: 'Villas' },
  { value: 'condominium', label: 'Condominiums' },
  { value: 'office_building', label: 'Office Buildings' },
  { value: 'store', label: 'Stores' },
  { value: 'shopping_mall', label: 'Shopping Malls' },
  { value: 'hotel', label: 'Hotel' },
  { value: 'resort', label: 'Resorts' },
  { value: 'distribution_center', label: 'Distribution Centers' },
  { value: 'industrial_site', label: 'Industrial Sites' },
  { value: 'multi_family_unit', label: 'Multi-Family Units' },
  { value: 'parking_site', label: 'Parking Sites' },
  { value: 'factory', label: 'Factories' },
  { value: 'warehouse', label: 'Warehouses' },
  { value: 'logistics_site', label: 'Logistics Sites' },
  { value: 'unit', label: 'Units' },
  { value: 'cold_storage', label: 'Cold Storage' },
  { value: 'recycling_center', label: 'Recycling Centers' },
  { value: 'data_center', label: 'Data Centers' },
  { value: 'aircraft_hangar', label: 'Aircraft Hangars' },
  { value: 'laboratory', label: 'Laboratories' },
  { value: 'transportation', label: 'Transportation' },
  { value: 'fuel_station', label: 'Fuel Stations' },
  { value: 'raw_land', label: 'Raw Land' },
  { value: 'development_land', label: 'Development Land' },
  { value: 'agricultural_land', label: 'Agricultural Land' },
  { value: 'future_development_land', label: 'Future Development Land' },
  { value: 'land_plot', label: 'Land Plots' },
  { value: 'riverside_land', label: 'Riverside Land' },
  { value: 'seaside_land', label: 'Seaside Land' },
  { value: 'supervised_land', label: 'Supervised Land' },
  { value: 'other', label: 'Other' }
];

export const amenities = [
  { value: 'beds', label: 'Beds' },
  { value: 'bathroom', label: 'Bath Room' },
  { value: 'kitchen', label: 'Kitchen' },
  { value: 'balcony_terrace', label: 'Balcony/Terrace' },
  { value: 'garden', label: 'Garden' },
  { value: 'pets_allowed', label: 'Pets Allowed' },
  { value: 'parking', label: 'Parking' },
  { value: 'wheelchair_accessible', label: 'Wheelchair Accessible' },
  { value: 'dishwasher', label: 'Dishwasher' },
  { value: 'washing_machine', label: 'Washing Machine' },
  { value: 'dryer', label: 'Dryer' },
  { value: 'air_conditioning', label: 'Air Conditioning' },
  { value: 'heating', label: 'Heating' },
  { value: 'assigned_parking', label: 'Assigned Parking' },
  { value: 'business_center', label: 'Business Center' },
  { value: 'carpet', label: 'Carpet' },
  { value: 'central_heat', label: 'Central Heat' },
  { value: 'concierge_service', label: 'Concierge Service' },
  { value: 'controlled_access', label: 'Controlled Access' },
  { value: 'deck', label: 'Deck' },
  { value: 'door_person', label: 'Door Person' },
  { value: 'dry_cleaning_service', label: 'Dry Cleaning Service' },
  { value: 'elevator', label: 'Elevator' },
  { value: 'ev_charging', label: 'EV Charging' },
  { value: 'fireplace', label: 'Fireplace' },
  { value: 'furnished', label: 'Furnished' },
  { value: 'garage_parking', label: 'Garage Parking' },
  { value: 'gym', label: 'Gym' },
  { value: 'hardwood_floor', label: 'Hardwood Floor' },
  { value: 'high_ceiling', label: 'High Ceiling' },
  { value: 'on_site_management', label: 'On Site Management' },
  { value: 'outdoor_space', label: 'Outdoor Space' },
  { value: 'package_service', label: 'Package Service' },
  { value: 'pool', label: 'Pool' },
  { value: 'residents_lounge', label: 'Residents Lounge' },
  { value: 'roof_deck', label: 'Roof Deck' },
  { value: 'storage', label: 'Storage' },
  { value: 'walk_in_closet', label: 'Walk-In Closet' },
  { value: 'beachfront', label: 'Beachfront' },
  { value: 'waterfront', label: 'Waterfront' },
  { value: 'ski_in_ski_out', label: 'Ski-in/Ski-out' },
  { value: 'smoke_alarm', label: 'Smoke Alarm' },
  { value: 'carbon_monoxide_alarm', label: 'Carbon Monoxide Alarm' },
  { value: 'instant_book', label: 'Instant Book' },
  { value: 'self_check_in', label: 'Self Check-in' },
  { value: 'hot_tub', label: 'Hot Tub' },
  { value: 'free_parking', label: 'Free Parking' },
  { value: 'crib', label: 'Crib' },
  { value: 'king_bed', label: 'King Bed' },
  { value: 'bbq_grill', label: 'BBQ Grill' },
  { value: 'breakfast', label: 'Breakfast' },
  { value: 'indoor_fireplace', label: 'Indoor Fireplace' },
  { value: 'smoking_allowed', label: 'Smoking Allowed' },
  { value: 'wifi', label: 'Wifi' },
  { value: 'private_attached_bathroom', label: 'Private Attached Bathroom' },
  { value: 'dedicated_workspace', label: 'Dedicated Workspace' },
  { value: 'tv', label: 'TV' },
  { value: 'hair_dryer', label: 'Hair Dryer' },
  { value: 'iron', label: 'Iron' }
];