export interface IAgency {
  _id: string;
  email: string;
  password: string;
  fullName: string;
  gender: string;
  dateOfBirth: string;
  nationality: string;
  nationalIdOrPassport: string;
  permanentAddress?: string;
  personalDocuments: string[];
  agencyLogo: string;
  agencyName: string;
  serviceDivision: string;
  serviceArea?: string;
  grade?: string;
  employees: string;
  officeAddress?: string;
  phoneNumberOffice: string;
  officeEmail: string;
  agencyDocuments: string[];
  description?: string;
  currency: string;
  feeAmount: number;
  depositAmount: number;
  agencyId: string;
  status: "Pending" | "Active" | "Inactive";
  twoFaAuthentication: boolean;
  ranking: number;
  socialLinks: { platform: string; link: string }[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}
